### ISSUE TITLE
webarchive hangs the app

### ISSUE THREAD

**Issue by ldenoue** [evernote/ios8-share-extension-demo#1]
whenever I choose webarchive, the EverNote app extension hangs...

**Comment by everic** [comment]
Hi, thank you for reporting this issue
I've filed a bug in our Jira system IOSNOTE-19158
If there's an update I'll let your know

Thank you!

**Comment by everic** [comment]
This is being fixed in our code base, and will be shipped with Evernote iOS 7.7.1. I've verified it myself. Thank you.
